### ISSUE TITLE
Error running npm start

### ISSUE THREAD

**Issue by ericjohannes** [datadesk/baker-example-page-template#4]
I cloned the repo, ran `npm install` and then `npm start` and I get an error

``` 
% npm start

> page-template@ start /projects/portfolio
> NODE_ENV=development bake serve --config

/Users/Eric.Blom.-ND/projects/portfolio/node_modules/@datagraphics/baker/bin/bake.js:4
import { bold, green, red } from 'colorette';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:811:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! page-template@ start: `NODE_ENV=development bake serve --config`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the page-template@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2023-01-26T17_35_39_299Z-debug.log
```

It seems like an issue related to the `import` syntax, which doesn't work with some node versions, but I am using node v 12.8 so I thought it would work.

**Comment by ericjohannes** [comment]
Well I misread the readme. My node is too old
